apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-capstone-deployment
  labels:
    app: my-capstone-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 3600
  replicas: 2
  selector:
    matchLabels:
      app: my-capstone-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-capstone-deployment
    spec:
      containers:
        - image: 130987/capstone:1.0
          imagePullPolicy: Always
          name: my-capstone-deployment
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-capstone-deployment
  labels:
    app: my-capstone-deployment
spec:
  type: LoadBalancer
  selector:
    app: my-capstone-deployment
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
